version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VARIANT: "18"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity