version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VARIANT: "18"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
      
  x11-bridge:
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "8080:8080"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8080"
      XPRA_PASSWORD: "SOMETHING"

  cypress:
    image: cypress/included:3.2.0
    depends_on: 
      - devcontainer
    environment:
      - CYPRESS_baseUrl=http://devcontainer:3000
    working_dir: /e2e
    volumes: 
      - ./:/e2e